### ISSUE TITLE
button to clear queue doesn't work

### ISSUE THREAD

**Issue by christubuntu** [namidaco/namida-snapshots#8]
That 1st button on the bottom left of the queue (which I suppose is for clearing the queue) doesn't do anything. Even if there is a queue, app always displays  "0 tracks removed" message.

https://github.com/user-attachments/assets/87689b32-4647-4d03-b52b-93393146a5ad

**Comment by MSOB7YY** [comment]
thats a button to remove duplicates, long press buttons like these to know what they do.

to clear a queue, make sure `Dismissible Queue` is enabled in extra settings and just swipe down the miniplayer
